### ISSUE TITLE
在video_data文件夹下，只生成了circle.mp4文件，没有生成keypoint_rotate.pkl

### ISSUE THREAD

**Issue by soluckysummer** [kleinlee/DH_live#14]
运行python data_preparation.py ***后，只生成了circle.mp4文件，没有生成keypoint_rotate.pkl

**Comment by yujun2019** [comment]
ExtractFromVideo 函数执行失败了

**Comment by TorrowL** [comment]
解决了吗

**Comment by TorrowL** [comment]
我解决了，data_preparation.py这个文件96行，那个循环里面的进度条删了就行了，这个进度条有bug
