### ISSUE TITLE
这个错误怎么解决呢

### ISSUE THREAD

**Issue by peano2** [kleinlee/DH_live#22]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by kleinlee** [comment]
maybe you installed pytorch with cpu version?
Run the followings to verify your pytorch version.
import torch
print(torch.cuda.is_available())
