### ISSUE TITLE
少量训练集超分后训练结果

### ISSUE THREAD

**Issue by qiuzi** [kleinlee/DH_live#24]
只用了5个视频作为训练 跑了15W轮的loss曲线
![loss](https://github.com/user-attachments/assets/4ff04f34-22c5-45e8-9bc1-beb88ea9c01e)
训练图像记录
![individualImage](https://github.com/user-attachments/assets/e7c95541-c441-4df4-88d9-a7245b62c973)
epoch_GI一直上涨这算正常吗？

再附上4k推理效果

https://github.com/user-attachments/assets/802db2db-8539-47a3-91a3-49b0bdfac2d2

音频跟嘴型不够恰合，还有如何扩大支持4K嘴部区域？

**Comment by kleinlee** [comment]
如果只用了5个视频训练，那必然过拟合了。 推理视频也只能用这五个视频，效果可能还不错，别的视频必然很糟糕。 
嘴型的匹配度取决于两个部分： 1是audio_encoder，这部分还没公开训练代码，是从wav2lip或剪映数字人蒸馏而来的，部分类似sadTalker的做法，但算力降低了几十倍。所以DH_live口型匹配度的上限不会超过wav2lip。 2是推理视频的口型和audio_encoder内嵌口型的相似度。
接下来空间时间较多。我会陆续补上训练还未公布的详细部分。

**Comment by xiaomaofei** [comment]
想问问DH_live你是怎么训练的？？？我试着跑上面的train.py.不是很行的通

**Comment by qiuzi** [comment]
> 想问问DH_live你是怎么训练的？？？我试着跑上面的train.py.不是很行的通

需要做预处理数据集 我在原有脚本上做了修改 `https://github.com/qiuzi/DH_live/raw/main/train_preparation.py`
根据代码路径需要在项目外建立对应文件夹

**Comment by tmige** [comment]
> > 想问问DH_live你是怎么训练的？？？我试着跑上面的train.py.不是很行的通
> 
> 需要做预处理数据集 我在原有脚本上做了修改 `https://github.com/qiuzi/DH_live/raw/main/train_preparation.py` 根据代码路径需要在项目外建立对应文件夹 更多的参数还是等作者说明吧，毕竟训练出来效果不太理想

face_mat_mask20240722.pkl这个文件在哪里下载的？

**Comment by qiuzi** [comment]
> > > 想问问DH_live你是怎么训练的？？？我试着跑上面的train.py.不是很行的通
> > 
> > 需要做预处理数据集 我在原有脚本上做了修改 `https://github.com/qiuzi/DH_live/raw/main/train_preparation.py` 根据代码路径需要在项目外建立对应文件夹 更多的参数还是等作者说明吧，毕竟训练出来效果不太理想
> 
> face_mat_mask20240722.pkl这个文件在哪里下载的？
> 
> Traceback (most recent call last):
>   File "D:\work\qiuzi\DH_live\train.py", line 58, in <module>
>     train_dict_info = data_preparation(video_list[:])
>   File "D:\work\qiuzi\DH_live\talkingface\data\few_shot_dataset.py", line 200, in data_preparation
>     with open(Path_output_pkl, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: '../preparation_bilibili\\d7adc87a-77e5-11ef-8e73-18c04d8055f1/face_mat_mask20240722.pkl'

项目库里搜一下
