### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by yancccc** [kleinlee/DH_live#28]
(dinet) ps@ps:/home/py/ycc/DH_live-main$ python train.py 
视频列表:  ['./1/circle.mp4']
video_selected final:  1
100%|█████████████████████████████████| 1/1 [00:00<00:00, 6808.94it/s]
train size:  0
训练字典信息:  {'driven_images': [], 'driven_keypoints': [], 'driving_keypoints': [], 'driven_mask_keypoints': []}
Traceback (most recent call last):
  File "/home/py/ycc/DH_live-main/train.py", line 63, in <module>
    raise ValueError("训练集为空！请检查数据加载和预处理步骤。")
ValueError: 训练集为空！请检查数据加载和预处理步骤。
没有生成训练字典信息

**Comment by kleinlee** [comment]
训练部分已更新，参见https://github.com/kleinlee/DH_live/tree/master/train
可以按这个再试试
