### ISSUE TITLE
内存泄漏 ?

### ISSUE THREAD

**Issue by Hujiazeng** [kleinlee/DH_live#3]
发现在运行过程中, 内存使用量持续增加

**Comment by kleinlee** [comment]
The code only provides a simple demonstration demo, but leaves a method which called AudioModel. reset() for clearing memory. If you want to build a formal product, you need to call this method at certain times according to your own usage scenario.

**Comment by kleinlee** [comment]
No crash and no memory leakage on my machine for 20+ minutes with reset method , please check your usage or attach detailed code. If someone else reports similar issues, I will reopen the problem.
