### ISSUE TITLE
请问 audiomodel的训练代码  可以开放吗

### ISSUE THREAD

**Issue by oaifaye** [kleinlee/DH_live#30]
请问 audiomodel的训练代码  可以开放吗

**Comment by kleinlee** [comment]
render训练部分已更新，参见https://github.com/kleinlee/DH_live/tree/master/train
audio部分的蒸馏模型还要再等几天。

**Comment by qwert1887** [comment]
非常感谢大佬作出的杰出贡献

**Comment by einsqing** [comment]
> render训练部分已更新，参见https://github.com/kleinlee/DH_live/tree/master/train audio部分的蒸馏模型还要再等几天。

@kleinlee 大佬，音频部分有进度么？

**Comment by LvHuaiSheng** [comment]
> > render训练部分已更新，参见https://github.com/kleinlee/DH_live/tree/master/train audio部分的蒸馏模型还要再等几天。
> 
> @kleinlee 大佬，音频部分有进度么？

++1

**Comment by DavidLi8910** [comment]
> render训练部分已更新，参见https://github.com/kleinlee/DH_live/tree/master/train audio部分的蒸馏模型还要再等几天。

@kleinlee 音频训练部分能开放么？
