### ISSUE TITLE
唇部训练集处理疑问

### ISSUE THREAD

**Issue by qiuzi** [kleinlee/DH_live#31]
如果我只提取`INDEX_LIPS`特征点进行训练，得到的模型能满足后面推理吗？

**Comment by kleinlee** [comment]
#1 可以看这里面的解释。关键点作为特征是不够的。现在前研的2D数字人也全部舍弃了关键点的做法

**Comment by qiuzi** [comment]
> #1 可以看这里面的解释。关键点作为特征是不够的。现在前研的2D数字人也全部舍弃了关键点的做法

眉毛到下巴呢？

**Comment by kleinlee** [comment]
嘴部之外的五官其他地方用关键点很适合。但嘴部很复杂，并不适合。 现在sota级别的都是end2end来学习嘴部的深层特征。
