### ISSUE TITLE
求大神帮助，为什么我的CPU100%,但是显存没用多少

### ISSUE THREAD

**Issue by yanglidaxian** [kleinlee/DH_live#32]
<img width="791" alt="86ced2d9f2601852b612141e1159238" src="https://github.com/user-attachments/assets/0e2dbcb4-40a2-4a48-ad59-49c5a2b183b3">

**Comment by qiuzi** [comment]
我这边也是 全是CPU在跑
![image](https://github.com/user-attachments/assets/93066bbc-c660-42cf-90f6-c7cec94607cc)

**Comment by kleinlee** [comment]
显存占用2GB是正常的。 CPU占用过高是因为每秒25帧高清图像的编解码，都是opencv库调用CPU完成的。所以如果运行在高分辨率视频上面，CPU会满载。

**Comment by qiuzi** [comment]
> 显存占用2GB是正常的。 CPU占用过高是因为每秒25帧高清图像的编解码，都是opencv库调用CPU完成的。所以如果运行在高分辨率视频上面，CPU会满载。

是render_model还是demo_avatar导致这样超线程占用？ 能否使用gpu进行编码加速？

**Comment by kleinlee** [comment]
> > 显存占用2GB是正常的。 CPU占用过高是因为每秒25帧高清图像的编解码，都是opencv库调用CPU完成的。所以如果运行在高分辨率视频上面，CPU会满载。
> 
> 是render_model还是demo_avatar导致这样超线程占用？ 能否使用gpu进行编码加速？

你可以按照自己需要修改cv2加载视频和显示画面的设置。渲染优化不在本项目的计划内。追求极致的性能体验可以关注我的另一个项目https://github.com/kleinlee/MiniMates。 也会加入数字人功能。 并保证ASR、LLM、TTS、数字人同时流畅运行在普通PC&手机设备上。

**Comment by qiuzi** [comment]
> > > 显存占用2GB是正常的。 CPU占用过高是因为每秒25帧高清图像的编解码，都是opencv库调用CPU完成的。所以如果运行在高分辨率视频上面，CPU会满载。
> > 
> > 
> > 是render_model还是demo_avatar导致这样超线程占用？ 能否使用gpu进行编码加速？
> 
> 你可以按照自己需要修改cv2加载视频和显示画面的设置。渲染优化不在本项目的计划内。追求极致的性能体验可以关注我的另一个项目[https://github.com/kleinlee/MiniMates。](https://github.com/kleinlee/MiniMates%E3%80%82) 也会加入数字人功能。 并保证ASR、LLM、TTS、数字人同时流畅运行在普通PC&手机设备上。

没开放
