### ISSUE TITLE
关于训练render

### ISSUE THREAD

**Issue by qwert1887** [kleinlee/DH_live#37]
再次感谢作者的伟大工作！现在有个问题，训练设置了160个epoch，我现在想在单人3分钟视频作为训练。160个epoch，也只随机用了视频里面的160帧图片，增加epoch到1w，改变lr策略，效果跟使用您的默认设置差不多，我想问下：
1、如果训练单人，是否可行？如果可行，是否应该将视频按照一定规则切片处理？
2、您的每一段训练视频的时长大概是多久？
3、您建议多少个视频片段合适呢？
感谢您@kleinlee

**Comment by kleinlee** [comment]
训练速度很快，所以你可以多试试。
关于训练，单人视频训练是可以的。 效果可以直观看tensorboard的图像，直到嘴部比较稳定且清晰。 因为训练是按照多人文件夹设置的。所以便捷的做法是把单人视频分为4个分视频（默认batch size=4）,然后按照正常的步骤来做。 
关于单人效果，除了render model的训练，还需要精细化audio模型产生的嘴型和单个人物具体嘴型的映射，也就是PCA的部分，这部分目前没有找到很好的办法。目前的映射追求的是通用性，所以对单人是有损失的，这也是没有使用end2end的弊端。

**Comment by lonngxiang** [comment]
Data Validation 这一步有作用吗，是否可以不用执行也行？

**Comment by lonngxiang** [comment]
tensorboard --logdir=checkpoint/Dinet_five_ref 查看怎么没数据
![image](https://github.com/user-attachments/assets/7e140aea-4398-43bc-ad78-e7642f7117dc)
有在训练
![image](https://github.com/user-attachments/assets/12f29bf0-b639-4ff1-bd27-5419c849d026)
![Uploading image.png…]()
