### ISSUE TITLE
训练效果问题

### ISSUE THREAD

**Issue by yancccc** [kleinlee/DH_live#38]
​​​​
![image](https://github.com/user-attachments/assets/c357fd7c-3505-4654-80eb-2b9de0d37a0a)
![image](https://github.com/user-attachments/assets/000022dd-f562-4a64-917f-4848c37fd09f)
使用几十个25帧视频训练160次的结果。请问该如何优化训练，能使得口齿清晰

**Comment by kleinlee** [comment]
继续训练下去呢，我并没有对单人做太多尝试？

**Comment by kleinlee** [comment]
从算法原理来说，dinet本身作为一个核心是wrap的few-shot算法，网络本身不保存颜色，而是学习怎么变形。 但对于单人talking face，更适合latend space的算法，譬如pix2pix、以及nerf类，它们自身就会存储物体的属性。你如果用wrap类的算法去学习单人，那只能边走边看了。经验之谈。

**Comment by yancccc** [comment]
我没有训练单人，我训练了几十个人，一般要训练多少次，能达到比较好的效果

**Comment by qiuzi** [comment]
效果可以啊，gl与dl 相互博弈在.251就算稳定，gl长时间上升趋势就要注意后面训练，中断后调低判别器学习率。但作者的训练代码貌似不支持中途修改学习率

**Comment by yancccc** [comment]
![image](https://github.com/user-attachments/assets/6fbf09b5-bc51-40cc-9375-f1730e014783)

**Comment by yancccc** [comment]
![image](https://github.com/user-attachments/assets/81181154-a4fe-4576-8b3f-12b48e6642ff)

**Comment by lonngxiang** [comment]
单人型个视频训练160轮，效果还是很差
![image](https://github.com/user-attachments/assets/aef6dc21-d33b-4996-8022-5155055d6abd)

**Comment by qiuzi** [comment]
> 单人型个视频训练160轮，效果还是很差
> ![image](https://github.com/user-attachments/assets/aef6dc21-d33b-4996-8022-5155055d6abd)
> 

6W轮试试

**Comment by lonngxiang** [comment]
> > 单人型个视频训练160轮，效果还是很差
> > ![image](https://private-user-images.githubusercontent.com/40717349/371719752-aef6dc21-d33b-4996-8022-5155055d6abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0OTU3MzEsIm5iZiI6MTcyNzQ5NTQzMSwicGF0aCI6Ii80MDcxNzM0OS8zNzE3MTk3NTItYWVmNmRjMjEtZDMzYi00OTk2LTgwMjItNTE1NTA1NWQ2YWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDAzNTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NmEzZTdiMDIyZWU4MzcwYjAyYTIyYTVmZTc0MGQ4Zjk3MDg2ZjdhYWUwNWRkZmNjYjdmYWRiOGZiNThhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PMgZbSn5eSbnvIN8xPW-N15kAEVGzW8MCNXd0aQBoUA)
> 
> 6W轮试试

哪个参数设置epcho呢，没看到

**Comment by lonngxiang** [comment]
找到了，有点隐秘config里，6w这得训练多久呀

**Comment by kleinlee** [comment]
epoch*总视频数，才是真正的训练步数。 默认设定的160轮，对于视频数有1000+的效果会比较稳定。 如果你的视频数只有几十个，那epoch最好增加相应比例来保证效果。

**Comment by lonngxiang** [comment]
> epoch*总视频数，才是真正的训练步数。 默认设定的160轮，对于视频数有1000+的效果会比较稳定。 如果你的视频数只有几十个，那epoch最好增加相应比例来保证效果。

只有5个单人视频，训练了3000轮效果还是很差

**Comment by kleinlee** [comment]
https://github.com/kleinlee/DH_live/issues/43#issuecomment-2381256877
参照这个。视频特别少的话可能不适合从头训练，可能需要加载一个的完整checkpoint来继续训练，我这两天放上来。

**Comment by zhangsanfather** [comment]
> 找到了，有点隐秘的配置里，6w这得训练多久呀

是哪一个文件呀
