### ISSUE TITLE
Unzip render.pth.gz file fail

### ISSUE THREAD

**Issue by CallMeHFK** [kleinlee/DH_live#4]
![image](https://github.com/user-attachments/assets/6ea769bd-097c-473c-a966-00b797279c0b)
1.git clone this project
2.unzip this two file --> fail

**Comment by yimikai** [comment]
did it solved?

**Comment by alants56** [comment]
Linux:
cat render.pth.gz.* > render.pth.gz
gzip -d render.pth.gz

**Comment by XeoOuYang** [comment]
在windows上
copy /b render.pth.gz.001 + render.pth.gz.002 render.pth.gz
gzip -d render.pth.gz

**Comment by fingerx** [comment]
另外一个解决方案 window 可以直接使用7zip 免费开源软件进行解压

**Comment by CallMeHFK** [comment]
> Linux: cat render.pth.gz.* > render.pth.gz gzip -d render.pth.gz

It works, thanks
