### ISSUE TITLE
能基于作者训练好的模型微调么？

### ISSUE THREAD

**Issue by einsqing** [kleinlee/DH_live#40]
能基于作者训练好的模型微调么？我测试了十几个 5 分钟的视频训练的，惨不忍睹

**Comment by kleinlee** [comment]
https://github.com/kleinlee/DH_live/issues/43#issuecomment-2381256877

一个checkpoint已上传 https://github.com/kleinlee/DH_live/blob/main/train/README.md#downloading-the-pre-trained-model。
