### ISSUE TITLE
模型训练过程中，报异常：AttributeError: 'NoneType' object has no attribute 'shape'，重现率几乎百分百

### ISSUE THREAD

**Issue by zhangziliang04** [kleinlee/DH_live#44]
![image](https://github.com/user-attachments/assets/51191b2f-b3b8-4aa1-8068-13de7bfd3c6e)

**Comment by kleinlee** [comment]
在错误的地方打印处理错误的图片名称，然后去相应位置查看一下图片是否存在。 代码只考虑视频人脸质量都很高的情况。 如果视频质量较差（譬如某一帧出现多个人脸或无人脸），需要自己写脚本处理。

**Comment by zhangziliang04** [comment]
确认了一下和路径无关，是基于cv2.imread(）函数带来的问题，前置处理保存的Png文件格式被破坏【如何保证保存不被破坏？】。导致返回的结果为None

**Comment by Eikwang** [comment]
遇到同样的问题

**Comment by Eikwang** [comment]
问题出在预处理环节，还没有找到是什么原因。已经尝试过重装opencv、VS运行库，重构环境。

**Comment by kleinlee** [comment]
我觉得更可能是ffmpeg的问题。
看一下这个
https://github.com/kleinlee/DH_live/blob/a8dbbfe0ccf9d3b4d80fb97df60894017f963152/train/data_preparation_face.py#L200
找到处理失败的视频，打印一下ffmpeg_cmd，自己在cmd中手动执行一下，看看是否成功。

**Comment by Eikwang** [comment]
重新安装了cuda、试过多个版本。python也换了几个版本。还是这样真是创鬼。试了一下在云平台部署成功了

**Comment by v3ucn** [comment]
是numpy版本的问题，请运行命令 pip3 install numpy==1.26.4  即可

**Comment by Eikwang** [comment]
> 是numpy版本的问题，请运行命令 pip3 install numpy==1.26.4 即可
> 
> 然后重新生成检查点文件

感谢大佬帮我解决。补充一下：视频人物肢体动作和头部晃动不能太大，不能有前后帧面部相差太大的剪辑
