### ISSUE TITLE
关于更换模型，提升唇形适用性但稍降低唇形准确性的调研

### ISSUE THREAD

**Issue by kleinlee** [kleinlee/DH_live#49]
DH_live是有两个版本，目前是基于像素PCA的还原，适用性稍差但准确率较高；还有一种是基于关键点轮廓的版本，基本对每一个形象的渲染结果都不会出bug，保证高清但准确率略有下降。 我看到不少人都反映在自己的数字人上面出现显示问题。 所以在这里问一下需要另一个版本的模型和代码吗。我在考虑把那一部分也补充上来。可以留言发表你们的想法。

**Comment by CyberWon** [comment]
可以单独开个分支，方便大家做个对比哦。

**Comment by LvHuaiSheng** [comment]
👍需要另一个版本的代码，建议在启动时可以指定参数来使用不同的策略还原

**Comment by qiuzi** [comment]
现有显卡大大满足现在性能，提升4倍对4090都有余

**Comment by qiuzi** [comment]
克隆自己作为情感与知识交流，这玩意对以后单身人群有帮助，文字AI始终不够眼神感官来的更直接，做成便捷普及话有前景

**Comment by einsqing** [comment]
支持修改为关键点，主要是视觉效果，其次才对嘴型

**Comment by Eikwang** [comment]
要不两个都支持呗，根据实际情况选择

**Comment by yuchen-gong** [comment]
对比了海外的lib syncer, 感觉DH_Live虽然进步不少，但生成出来的数字人，嘴部变化太大，导致跟原始人物都不像了。
请教下，这个问题您打算怎么优化呢？

**Comment by kleinlee** [comment]
> 对比了海外的lib syncer, 感觉DH_Live虽然进步不少，但生成出来的数字人，嘴部变化太大，导致跟原始人物都不像了。 请教下，这个问题您打算怎么优化呢？
正如这个issue说的，等我发另一个版本吧。 使用关键点来做，自然度没什么问题。

**Comment by kleinlee** [comment]
> 克隆自己作为情感与知识交流，这玩意对以后单身人群有帮助，文字AI始终不够眼神感官来的更直接，做成便捷普及话有前景

想法不谋而合。 但我在图片数字人这一脉彻底面向普通人群，逐渐做到普通电脑、手机、网页都能实时。视频数字人对口型整体还是太呆了，不会作为主干技术。

**Comment by qiuzi** [comment]
> > 克隆自己作为情感与知识交流，这玩意对以后单身人群有帮助，文字AI始终不够眼神感官来的更直接，做成便捷普及话有前景
> 
> 想法不谋而合。 但我在图片数字人这一脉彻底面向普通人群，逐渐做到普通电脑、手机、网页都能实时。视频数字人对口型整体还是太呆了，不会作为主干技术。

图片数字人对整体躯干不友好吧？ 下半身都不能变动有种恐怖谷效应

**Comment by kleinlee** [comment]
> > > 克隆自己作为情感与知识交流，这玩意对以后单身人群有帮助，文字AI始终不够眼神感官来的更直接，做成便捷普及话有前景
> > 
> > 
> > 想法不谋而合。 但我在图片数字人这一脉彻底面向普通人群，逐渐做到普通电脑、手机、网页都能实时。视频数字人对口型整体还是太呆了，不会作为主干技术。
> 
> 图片数字人对整体躯干不友好吧？ 下半身都不能变动有种恐怖谷效应

需要逐步解决，而且有不同的技术方案。 基于GAN或Diffusion的纯粹渲染方案，需要从头部控制---上半身晃动---手部控制---头发服装模拟逐步解决，前两部分是很容易的。 而基于3D gaussian splatting的方案更是适用于此类，渲染速度也非常快。
而且大量的场景不需要下半身，只要做好上半身就行了。 AI女友、AI主播、AI亲人、AI客服等

**Comment by qiuzi** [comment]
> > > > 克隆自己作为情感与知识交流，这玩意对以后单身人群有帮助，文字AI始终不够眼神感官来的更直接，做成便捷普及话有前景
> > > 
> > > 
> > > 想法不谋而合。 但我在图片数字人这一脉彻底面向普通人群，逐渐做到普通电脑、手机、网页都能实时。视频数字人对口型整体还是太呆了，不会作为主干技术。
> > 
> > 
> > 图片数字人对整体躯干不友好吧？ 下半身都不能变动有种恐怖谷效应
> 
> 需要逐步解决，而且有不同的技术方案。 基于GAN或Diffusion的纯粹渲染方案，需要从头部控制---上半身晃动---手部控制---头发服装模拟逐步解决，前两部分是很容易的。 而基于3D gaussian splatting的方案更是适用于此类，渲染速度也非常快。 而且大量的场景不需要下半身，只要做好上半身就行了。 AI女友、AI主播、AI亲人、AI客服等

https://github.com/Fictionarry/TalkingGaussian.git 说的是这个吗？ 听说还原度很高，但头发这样的会不会失真

**Comment by kleinlee** [comment]
> > > > > 克隆自己作为情感与知识交流，这玩意对以后单身人群有帮助，文字AI始终不够眼神感官来的更直接，做成便捷普及话有前景
> > > > 
> > > > 
> > > > 想法不谋而合。 但我在图片数字人这一脉彻底面向普通人群，逐渐做到普通电脑、手机、网页都能实时。视频数字人对口型整体还是太呆了，不会作为主干技术。
> > > 
> > > 
> > > 图片数字人对整体躯干不友好吧？ 下半身都不能变动有种恐怖谷效应
> > 
> > 
> > 需要逐步解决，而且有不同的技术方案。 基于GAN或Diffusion的纯粹渲染方案，需要从头部控制---上半身晃动---手部控制---头发服装模拟逐步解决，前两部分是很容易的。 而基于3D gaussian splatting的方案更是适用于此类，渲染速度也非常快。 而且大量的场景不需要下半身，只要做好上半身就行了。 AI女友、AI主播、AI亲人、AI客服等
> 
> https://github.com/Fictionarry/TalkingGaussian.git 说的是这个吗？ 听说还原度很高，但头发这样的会不会失真

学术界对gaussian的用法和工业界还不匹配，这一部分未来的使用方式还有待观察。 目前来看最佳的实践方式，是diffusion直接进行3D gaussian建模，这部分算力要求很高，数据也缺少。字节华为的团队已经开始做探索了。估计还需要1年时间才有爆发。

**Comment by dasdadaosijda** [comment]
大佬，可以开源一下audio LSTM训练的代码呢@

**Comment by kleinlee** [comment]
已更新一个超轻量级的给予关键点的版本，算力不到50 m flops，详情请看readme
