### ISSUE TITLE
训练问题:可以选择侧脸的数据进行训练吗?

### ISSUE THREAD

**Issue by logo66612** [kleinlee/DH_live#53]
训练问题:可以选择侧脸的数据进行训练吗?

**Comment by kleinlee** [comment]
目前这个版本不支持。 可以再等几天，我10月末会上传基于关键点的方案。 关键点的方案在45度偏转内都有一定的效果。

**Comment by kleinlee** [comment]
原计划的关键点的方案公布意义已经不大，已发布依赖关键点的DH_live_mini，在轻量规模上是SOTA级别的。
