### ISSUE TITLE
最后返回视频，音频和画面时长不一致，是对传入的音频有什么特殊要求？

### ISSUE THREAD

**Issue by hjj-lmx** [kleinlee/DH_live#54]
https://github.com/user-attachments/assets/e918926c-12bc-4541-85f5-bbe014e76c7b

**Comment by hjj-lmx** [comment]
https://github.com/user-attachments/assets/878d8930-5f61-4455-b33e-6958d03dee12

**Comment by kleinlee** [comment]
语音需要16K采样率，单通道。 readme里面有说明。 这个视频采样率是24k赫兹。

**Comment by hjj-lmx** [comment]
> 语音需要16K采样率，单通道。 readme里面有说明。 这个视频采样率是24k赫兹。

tran里面的与训练模型怎么转换为可用render.pth，下载后直接使用不了，是解压出来的效果好点，还是哪个预训练的好点

**Comment by hjj-lmx** [comment]
> 语音需要16K采样率，单通道。readme里面有说明。这个视频采样率为24kHz。

![image](https://github.com/user-attachments/assets/95920116-0ca2-4a2a-b127-97107897e615)
我这么修改后，嘴巴都不动了

**Comment by kleinlee** [comment]
> > 语音需要16K采样率，单通道。 readme里面有说明。 这个视频采样率是24k赫兹。
> 
> tran里面的与训练模型怎么转换为可用render.pth，下载后直接使用不了，是解压出来的效果好点，还是哪个预训练的好点

一样的， training的模型使用可以看issue区的回复，提取里面的net_g来使用。

**Comment by hjj-lmx** [comment]
> 语音需要16K采样率，单通道。 readme里面有说明。 这个视频采样率是24k赫兹。

感觉生成的不稳定，有时候嘴巴会在一个区域内晃动
