### ISSUE TITLE
训练预处理时一堆这样的提示 能关闭掉吗？

### ISSUE THREAD

**Issue by qiuzi** [kleinlee/DH_live#58]
`I0000 00:00:1729329225.159320  595296 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5it/s]
I0000 00:00:1729329225.186432  611692 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 560.35.03), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
W0000 00:00:1729329225.193730  611687 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1729329225.209006  595296 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729329225.235839  611717 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 560.35.03), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
W0000 00:00:1729329225.236897  611700 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1729329225.244573  611706 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1729329225.258071  595296 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729329225.285311  611725 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 560.35.03), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
`

**Comment by kleinlee** [comment]
#66
