### ISSUE TITLE
推理后视频消失，output文件夹为空

### ISSUE THREAD

**Issue by leetraman822** [kleinlee/DH_live#6]
在推理时output文件夹内会产生一个包含视频文件的文件夹，推理完成后该文件夹消失，output一片空白。后台没有报错。不知道什么情况。
以下是cmd内容：

(dhlive) F:\SoVITS\DH_live>python demo.py video_data/test video_data/audio0.wav 1.mp4
(256, 256, 3)
Video path is set to: video_data/test
Audio path is set to: video_data/audio0.wav
output video name is set to: 1.mp4
C:\Users\Administrator\anaconda3\envs\dhlive\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator PCA from version 1.3.0 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
F:\SoVITS\DH_live\talkingface\audio_model.py:47: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.__net.load_state_dict(torch.load(ckpt_path))
F:\SoVITS\DH_live\talkingface\render_model.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(ckpt_path)
  0%|                                                                                          | 0/186 [00:00<?, ?it/s]C:\Users\Administrator\anaconda3\envs\dhlive\Lib\site-packages\torch\nn\functional.py:4373: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
100%|████████████████████████████████████████████████████████████████████████████████| 186/186 [00:09<00:00, 18.74it/s]

**Comment by kleinlee** [comment]
注意输入的参数的含义，1.mp4才是你生成的文件，output内部的文件会在生成后被删除。

**Comment by leetraman822** [comment]
> 注意输入的参数的含义，1.mp4才是你生成的文件，output内部的文件会在生成后被删除。
如果最终结果不在output文件夹的话，我不知道视频被保存到哪里了。
我尝试了主页提供的指令：
python demo.py video_data/test video_data/audio0.wav 1.mp4
推理完成后找不到保存的文件。
我尝试将1.mp4改为目录+文件名：
python demo.py video_data/test video_data/audio0.wav 输出目录/XX.mp4，
也同样没有文件。
不管是用自己的，还是video data目录自带的素材，都没有视频被保存。

**Comment by kleinlee** [comment]
应该就是工程根目录下的1.mp4。 如果输出目录是你自定义的，目录不要带中文同时保证目录文件夹存在。

**Comment by KelvinHuang66** [comment]
the same question
check demo.py line 57  
"ffmpeg -i {} -i {} -c:v libx264 -pix_fmt yuv420p -loglevel quiet {}".format(save_path, wavpath, output_video_name))“

**Comment by KelvinHuang66** [comment]
-c:v copy 可以解决问题

**Comment by yongsuH** [comment]
Change line 57 in demo.py to this worked out for me:
    "ffmpeg -i {} -i {} -c:v copy -pix_fmt yuv420p -loglevel quiet {}".format(save_path, wavpath, output_video_name))
