### ISSUE TITLE
使用train/data_preparation_face.py 一直报以下信息

### ISSUE THREAD

**Issue by DavidLi8910** [kleinlee/DH_live#66]
使用train/data_preparation_face.py 一直报以下信息怎么解决呢？

我的环境（python=3.12.4）如下：
kaldi-native-fbank==1.19.1
mediapipe==0.10.18
sounddevice==0.4.6
tqdm==4.66.4
scikit-learn==1.3.0
tensorboard==2.18.0
facexlib>=0.2.5
lmdb==1.5.1
numpy==1.26.4
opencv-python==4.9.0.80
scipy==1.14.1
moviepy==1.0.3
pydub==0.25.1
tensorflow==2.18.0
soundfile==0.12.1
wavinfo==3.0.0
librosa==0.10.2
numba==0.59.1

W0000 00:00:1730602250.370104    3044 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602250.569997    3088 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602250.767403    3041 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602250.879456    3094 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602250.879459    3141 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602251.277836    3146 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602251.468018    3154 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602251.778639    3206 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602251.781908    3213 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602251.868557    3167 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602251.976290    3220 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602252.173633    3225 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1730602252.177576    3278 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

**Comment by chuhuan88** [comment]
我也是，请问楼主解决了吗

**Comment by kleinlee** [comment]
python版本太高，mediapipe库有点没跟上。 警告信息忽略就行，不影响结果。 至于为什么用这么高的版本。版本库越新越简单，项目存续的时间就越长，所以才指定了一切都是最新的库。
