### ISSUE TITLE
已经训练2万步了，Loss_perception: 1.5501 ，我想继续训练如何操作

### ISSUE THREAD

**Issue by selifecn** [kleinlee/DH_live#68]
已经训练2万步了，Loss_perception: 1.5501 ，但是效果还是不够，我想继续训练如何操作呢？

**Comment by selifecn** [comment]
每次都是从头开始，确实很费时间呢

**Comment by DavidLi8910** [comment]
> 已经训练2万步了，Loss_perception: 1.5501 ，但是效果还是不够，我想继续训练如何操作呢？

train\train_render_model.py 加上以下：
if __name__ == "__main__":
    opt.resume = True
    opt.resume_path = "需要继续训练的模型"

并且把  # opt.start_epoch = checkpoint['epoch']  注释去掉，就可以了。

**Comment by selifecn** [comment]
非常感谢！
