### ISSUE TITLE
音频模型训练疑问

### ISSUE THREAD

**Issue by DavidLi8910** [kleinlee/DH_live#69]
preparation_step0.py
通过一张图片和音频文件，使用wav2lip模型生成视频。但是因为wav2lip官方模型限制只能生成96的低清晰度的视频。这样是否会影响音频模型的训练效果？如果我有高清视频是否可以直接使用呢？

preparation_step1.py
里面把嘴部分辨率设置成了[30, 15] ，如果用高清视频进行训练音频模型那这个值应该怎么设置呢？

**Comment by kleinlee** [comment]
音频模型主要是预测嘴部的大致变化规律，回归的嘴部区域大一点小一点影响不大。 是否可以生成高清几乎全部依赖dinet。  当然那如果你想试试不同的配置，也可以随意魔改，嘴部分辨率按需要随意设定都行。

**Comment by qiuzi** [comment]
公版wav2lip 用的是英文数据集，中文会有影响吗？还是需要重新训练一套中文模型？MuseTalk 对中文嘴型比较好，能否也蒸馏？
