### ISSUE TITLE
在训练数据中模糊的图片可以直接删除吗？

### ISSUE THREAD

**Issue by selifecn** [kleinlee/DH_live#70]
在训练数据中发现大量模糊的图片，牙齿轮廓不清晰，这样的图片会影响模型训练效果吗？直接删除会不会提高模型的质量，以及提高模型训练速度？

**Comment by Eikwang** [comment]
似乎不行。我已经不玩这个项目了，[Ultralight-Digital-Human](https://github.com/anliyuan/Ultralight-Digital-Human)x效果更好

**Comment by Eikwang** [comment]
我试过，删了报错，替换也报错

**Comment by kleinlee** [comment]
> 在训练数据中发现大量模糊的图片，牙齿轮廓不清晰，这样的图片会影响模型训练效果吗？直接删除会不会提高模型的质量，以及提高模型训练速度？

高清质量当然会提升模型的效果。 只是现有程序如果删除个别图片确实会导致程序失败，所以要删除的话可以删掉那些模糊的整个视频文件夹。也就是要删就删掉整个文件夹而不是单个图片。 或者就是你要魔改预处理程序。
