### ISSUE TITLE
训练的视频数据有什么要求么

### ISSUE THREAD

**Issue by zeushera140** [kleinlee/DH_live#75]
是不是只能一个人脸？有BGM会影响训练么？
谢谢大佬们

**Comment by TianQi7723** [comment]
我是25个不同人脸训练的，效果还不错，最起码嘴不歪了正常了

**Comment by zeushera140** [comment]
> 我是25个不同人脸训练的，效果还不错，最起码嘴不歪了正常了

我试试。

**Comment by kleinlee** [comment]
每个视频的每一帧都只能有一个人脸。 对声音没有要求。
