### ISSUE TITLE
这个安装环境需要python 那个版本

### ISSUE THREAD

**Issue by anstonjie** [kleinlee/DH_live#8]
这个安装环境需要python 那个版本

**Comment by fingerx** [comment]
python 3.10 安装成功，测试成功，window @anstonjie

**Comment by anstonjie** [comment]
牛



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月07日 14:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [kleinlee/DH_live] 这个安装环境需要python 那个版本 (Issue #8) |

python 3.10 安装成功，测试成功，window @anstonjie
