### ISSUE TITLE
同时加载多个模型时，最有最后一个模型可用

### ISSUE THREAD

**Issue by lddcdut** [kleinlee/DH_live#84]
我在models文件夹下有多个模型，按顺序加载后，只有最后一个模型可以推理
models_dict = {}
model_names = ["model1", "model2", "model3", "model4", "model5"]  
for model_name in model_names:
    renderModel = RenderModel()
    renderModel.loadModel("checkpoint/render.pth")
    pkl_path = f"models/{model_name}/keypoint_rotate.pkl"
    video_path = f"models/{model_name}/circle.mp4"
    renderModel.reset_charactor(video_path, pkl_path)
    models_dict[model_name] = renderModel

只有models_dict["model5"].interface(frame)可用，看了下render_model.py，也没发现什么问题。

**Comment by SunOfHomeBoy** [comment]
请问一下，同时加载多个模型 能提升效果么？
